#!/usr/bin/python3
import sys
import getopt

import matplotlib.pyplot as plt
import matplotlib.cm as cm

from src.maze import Maze

def print_help():
    with open("src/help.txt") as f:
        print(f.read())

def main():
    argv = sys.argv[1:]
    opt, argv = getopt.getopt(argv, 'H', ["help", "color=", "animate", "cli", "speed="])
    ac = len(argv)
    optc = len(opt)

    all_colors = plt.colormaps()
    plt_color = 'gray'
    is_show = True
    is_animate = False
    is_cli = False
    speed = 100

    for a, b in opt:
        if a == '-H' or a == "--help":
            print_help()
            return 0
        if a == "--color":
            if b in all_colors:
                plt_color = b
            else:
                print("Color not are in the color map of matplotlib check this in :\nhttps://matplotlib.org/stable/tutorials/colors/colormaps.html#grayscale-conversion")
                return 1
        if a == '--animate':
            is_animate = True
            is_show = False
            is_cli = False
        if a == '--cli':
            is_show = False
            is_animate = False
            is_cli = True
        if a[0:9] == '--speed':
            is_animate = True
            is_show = False
            is_cli = False
            speed = 100/float(b)

    try:
        filepath = argv[0]
        with open(filepath) as f:
            maze = f.read()
    except:
        print("Bad Filepath")
        return 1
    maze = [[_ for _ in i] for i in maze.split("\n")]
    maze = Maze(maze, plt_color)

    if is_show:
        maze.show()
    if is_animate:
        maze.animate(speed)
    if is_cli:
        if maze.solve != False:
            exit(len(maze.solve))
        else:
            exit(0)

if __name__ == "__main__":
    main()